CityRep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("login.urls")),
    path("admin/", admin.site.urls),
    path("main/", include("main.urls")),
    path("traffic/", include("traffic.urls")),
    path("population/", include("population.urls")),
    path("economy/", include("economy.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

economy/urls.py
from django.urls import path
from . import views

app_name = "economy"
urlpatterns = [
    path("introduction/", views.IntroductionView.as_view(), name="introduction"),
    path("representation_train/", views.RepresentationTrainView.as_view(), name="representation_train"),
    path("representation_pre/", views.RepresentationPreView.as_view(), name="representation_pre")
]

login/urls.py
from django.urls import path
from . import views
from main.views import IndexView 

app_name = "login"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout")
]

main/urls.py
from django.urls import path

from . import views
from django.contrib.auth.decorators import login_required


app_name = "main"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

population/urls.py
from django.urls import path
from . import views

app_name = "population"
urlpatterns = [
    path("introduction/", views.IntroductionView.as_view(), name="introduction"),
    path("representation_train/", views.RepresentationTrainView.as_view(), name="representation_train"),
    # path("representation_upload/", views.RepresentationUploadView.as_view(), name="representation_upload"),
    path("representation_pre/", views.RepresentationPreView.as_view(), name="representation_pre"),
    
]

traffic/urls.py
from django.urls import path
from . import views

app_name = "traffic"
urlpatterns = [
    path("introduction/", views.IntroductionView.as_view(), name="introduction"),
    path("representation_train/", views.RepresentationTrainView.as_view(), name="representation_train"),
    path("representation_upload/", views.RepresentationUploadView.as_view(), name="representation_upload"),
    path("representation_pre/", views.RepresentationPreView.as_view(), name="representation_pre"),
    path("speed_prediction/", views.SpeedPredicitonView.as_view(), name="speed_prediction"),
    path("speed_prediction_upload/", views.SpeedPredictionUploadView.as_view(), name="speed_prediction_upload"),
    path("route_plan/", views.RoutePlanView.as_view(), name="route_plan"),
    path("route_plan_upload/", views.RoutePlanUploadView.as_view(), name="route_plan_upload"),
    path("route_plan_train/", views.RoutePlanTrainView.as_view(), name="route_plan_train"),
    path("next_loc_prediction/", views.NextLocPredictionView.as_view(), name="next_loc_prediction"),
    path("next_loc_prediction_upload/", views.NextLocPredictionUploadView.as_view(), name="next_loc_prediction_upload"),
    path("next_loc_prediction_train/", views.NextLocPredictionTrainView.as_view(), name="next_loc_prediction_train"),
    path("accident/", views.AccidentView.as_view(), name="accident"),
    path("accident_upload/", views.AccidentUploadView.as_view(), name="accident_upload")
]

population/models.py
from django.db import models

# Create your models here.

population/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class IntroductionView(LoginRequiredMixin, View):

    def get(self, request):
        template = "population/introduction.html"
        return render(request, template)

class RepresentationTrainView(LoginRequiredMixin, View):

    def get(self, request):
        template = "population/representation_train.html"
        return render(request, template)

class RepresentationPreView(LoginRequiredMixin, View):

    def get(self, request):
        template = "population/representation_pre.html"
        return render(request, template)

population/templates/population/introduction.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title> 城市体征构建与认知系统 </title>
  <link rel="icon" href="#"/>

  <!-- Bootstrap -->
  <link href=" {% static 'assets/css/bootstrap.min.css' %} " rel="stylesheet">
  <!-- Font Awesome -->
  <link href=" {% static 'assets/css/font-awesome.min.css' %} " rel="stylesheet">
  <!-- Dropzone.js -->
  <!-- <link href=" {% static 'assets/css/dropzone.min.css" rel="stylesheet"> -->

  <!-- Custom Theme Style -->
  <link href=" {% static 'assets/css/custom.min.css' %} " rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{% url 'main:index' %}" class="site_title"><i class="fa fa-home"></i><span
              style="font-weight:bolder; font-size:22px;">CityRep System</span></a>            
          </div>
          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <p style="text-align: center; font-weight:bolder; font-size:20px; color: white;"> 城市体征构建与认知系统 </p>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3 style="text-align: left;  font-size:15px; color: white;">目录</h3>
              <ul class="nav side-menu">
                <li><a><i class="fa fa-car"></i> 城市交通体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'traffic:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'traffic:representation_train' %}">表征建模</a></li>
                    <li><a href="{% url 'traffic:representation_pre' %}">表征展示</a></li>
                    <li><a href="{% url 'traffic:speed_prediction' %}">速度预测</a></li>
                    <li><a href="{% url 'traffic:route_plan' %}">路径规划</a></li>
                    <li><a href="{% url 'traffic:next_loc_prediction' %}">下一跳预测</a></li>
                    <li><a href="{% url 'traffic:accident' %}">事故推演</a></li>
                    </li>
                  </ul>
                </li>
                <li><a><i class="fa fa-male"></i> 城市人口体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'population:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'population:representation_train' %}">流动建模</a></li>
                    <li><a href="{% url 'population:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-line-chart"></i> 城市经济体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'economy:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'economy:representation_train' %}">指标分析</a></li>
                    <li><a href="{% url 'economy:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>
          <nav class="navbar navbar-expand-lg">
            <div class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
                <span class="navbar-text mr-3" style="font-size: 16px;">当前在线： {{ request.user.username }}</span>
                <form action="{% url 'login:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link" style="font-size: 16px;">退出</button>
                </form>
              {% else %}
                <a href="{% url 'login:login' %}" class="btn btn-link">登录</a>
                <a href="{% url 'login:register' %}" class="btn btn-link">注册</a>
              {% endif %}
            </div>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">

        <div class="row">
          <div class="col-md-12 col-sm-12">
            <div class="x_panel">
              <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <p style="text-align: center; font-weight:bolder; font-size:30px;">模型介绍</p>
              </div>
              <div class="x_content" style="text-align: left; font-weight: normal; font-size:20px">
                <p style="text-indent: 2em;">
                  人口表征建模是指对人口进行建模和描述的过程，以便更好地了解和预测人口的特征和行为。人口表征建模在许多领域都非常重要，例如公共政策、市场营销、医疗保健和社会科学等领域。人口表征建模主要包括人口统计学方法、人口地理学方法和社会网络分析方法。本系统重点基于雄安新区人口统计特点和地理位置信息进行建模，以了解人口的地理特征和流动趋势，有助于优化城市资源配置，规划城市发展方向，加强城市风险管理等。
                </p>
                <p style="text-indent: 2em;">
                  本系统采用了一种全新的可解释的时空深度学习模型来建模城市人口表征。其主要思想是类比由重力势能场驱动的水流，通过建立一些潜在的时空势能场来模拟城市人口分布和流动趋势。为了实现这一效果，本系统利用一种风场分解算法，将人口迁移活动分解为多个树状分量，从而建立可解释的时空势能场。并设计一个由时间组件(建模时间相关性)和空间组件(建模空间依赖性)组成的时空深度学习模型进行建模。
                </p>
                <p style="font-weight: bolder; font-size: 25px;">
                  模型框架图
                </p>
                <p style="text-align: center;">
                  <img src="../../static/assets/img/PEF.png" weight="700px" height="800px">
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- /page content -->

    </div>
  </div>

  <!-- jQuery -->
  <script src=" {% static 'assets/js/jquery.min.js' %} "></script>
  <!-- Bootstrap -->
  <script src=" {% static 'assets/js/bootstrap.bundle.min.js' %} "></script>
  <!-- Dropzone.js -->
  <!-- <script src=" {% static 'assets/js/dropzone.min.js' %} "></script> -->
  <script src=" {% static 'assets/js/jquery.cookie.js' %} "></script>

  <!-- Custom Theme Scripts -->
  <script src=" {% static 'assets/js/custom.min.js' %} "></script>

</body>
</html>

population/templates/population/representation_pre.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title> 城市体征构建与认知系统 </title>
  <link rel="icon" href="#"/>

  <!-- Bootstrap -->
  <link href=" {% static 'assets/css/bootstrap.min.css' %} " rel="stylesheet">
  <!-- Font Awesome -->
  <link href=" {% static 'assets/css/font-awesome.min.css' %} " rel="stylesheet">

  <!-- Leaflet-->
  <link href=" {% static 'assets/css/leaflet.css' %} " rel="stylesheet">
  <!-- Custom Theme Style -->
  <link href=" {% static 'assets/css/custom.min.css' %} " rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{% url 'main:index' %}" class="site_title"><i class="fa fa-home"></i><span
                style="font-weight:bolder; font-size:22px;">CityRep System</span></a>
          </div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <p style="text-align: center; font-weight:bolder; font-size:20px; color: white;"> 城市体征构建与认知系统 </p>
          </div>
          <!-- /menu profile quick info -->
          <br />
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3 style="text-align: left;  font-size:15px; color: white;">目录</h3>
              <ul class="nav side-menu">
                <li><a><i class="fa fa-car"></i> 城市交通体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'traffic:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'traffic:representation_train' %}">表征建模</a></li>
                    <li><a href="{% url 'traffic:representation_pre' %}">表征展示</a></li>
                    <li><a href="{% url 'traffic:speed_prediction' %}">速度预测</a></li>
                    <li><a href="{% url 'traffic:route_plan' %}">路径规划</a></li>
                    <li><a href="{% url 'traffic:next_loc_prediction' %}">下一跳预测</a></li>
                    <li><a href="{% url 'traffic:accident' %}">事故推演</a></li>
                    </li>
                  </ul>
                </li>
                <li><a><i class="fa fa-male"></i> 城市人口体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'population:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'population:representation_train' %}">流动建模</a></li>
                    <li><a href="{% url 'population:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-line-chart"></i> 城市经济体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'economy:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'economy:representation_train' %}">指标分析</a></li>
                    <li><a href="{% url 'economy:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>
          <nav class="navbar navbar-expand-lg">
            <div class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
                <span class="navbar-text mr-3" style="font-size: 16px;">当前在线： {{ request.user.username }}</span>
                <form action="{% url 'login:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link" style="font-size: 16px;">退出</button>
                </form>
              {% else %}
                <a href="{% url 'login:login' %}" class="btn btn-link">登录</a>
                <a href="{% url 'login:register' %}" class="btn btn-link">注册</a>
              {% endif %}
            </div>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">
        <div class="page-title">
          <div class="title_left">
            <h3>人口表征建模</h3>
          </div>
        </div>
        
        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12">

            <div class="x_panel">
              <div class="x_title">
                <h2>速度预测</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="#">Settings 1</a>
                        <a class="dropdown-item" href="#">Settings 2</a>
                      </div>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>

              <div class="x_content">
                <div class="row v-align">
                  <div class="col-md-6 col-sm-6">
                    <form action="" method="post" enctype="multipart/form-data" id="form">
                      {% csrf_token %}
                      <div class="col-md-8 col-sm-8">
                        <div class="item form-group">
                          <label class="col-form-label col-md-6 col-sm-6 offset-md-2 label-align" for="epochs" style="vertical-align: middle">历史数据: </span></label>
                          <div class="col-md-6 col-sm-6">
                            <input type="file" id="upload_file" required="required" class="form-control parameter" style="color: gray">
                          </div>
                        </div>
                      </div>
                      <div class="col-md-2 col-sm-2 offset-md-1 offset-sm-1">
                        <button class="btn btn-info form-control upload-btn" name="type" type="submit" id="upload">上传</button>
                      </div>
                    </form>
                  </div>
                  <div class="col-md-6 col-sm-6 justify-content-start">
                    <form action="" method="post" enctype="multipart/form-data" id="form">
                      <div class="col-md-4 col-sm-4" style="float:left">
                        <div class="item form-group">
                          <label class="col-form-label col-md-8 col-sm-8 offset-md-1 label-align" for="batch_size">预测时间（分钟）: </span></label>
                          <div class="col-md-6 col-sm-6 ">
                            <input type="text" id="pred_time" required="required" class="form-control parameter" value="10" style="color: gray">
                          </div>
                        </div>
                      </div>
                      <div class="col-md-2 col-sm-2 offset-md-1 offset-sm-1">
                        <button class="btn btn-info form-control upload-btn" name="type" type="submit" id="pred">预测</button>
                      </div>
                    </form>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12 col-sm-12">
                    <div id="mapid" style="height: 680px;"></div>
                  </div>
                </div>
              </div>
              <div style="height:260px; width:100%; display:none; overflow-y:auto" >
                <table class="table table-striped" id="result1"></table>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

      </div>
      <!-- /page content -->

    </div>
  </div>

  <!-- jQuery -->
  <script src=" {% static 'assets/js/jquery.min.js' %} "></script>
  <script src=" {% static 'assets/js/leaflet.js' %} "></script>
  <!-- Bootstrap -->
  <script src=" {% static 'assets/js/bootstrap.bundle.min.js' %} "></script>
  <script src=" {% static 'assets/js/jquery.cookie.js' %} "></script>

  <script src=" {% static 'assets/js/potential_energy.js' %} "></script>

  <!-- Custom Theme Scripts -->
  <script src=" {% static 'assets/js/custom.min.js' %} "></script>

</body>

</html>

population/templates/population/representation_train.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title> 城市体征构建与认知系统 </title>
  <link rel="icon" href="#"/>

  <!-- Bootstrap -->
  <link href=" {% static 'assets/css/bootstrap.min.css' %} " rel="stylesheet">
  <!-- Font Awesome -->
  <link href=" {% static 'assets/css/font-awesome.min.css' %} " rel="stylesheet">
  <!-- Dropzone.js -->
  <!-- <link href=" {% static 'assets/css/dropzone.min.css" rel="stylesheet"> -->

  <!-- Custom Theme Style -->
  <link href=" {% static 'assets/css/custom.min.css' %} " rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="{% url 'main:index' %}" class="site_title"><i class="fa fa-home"></i><span
              style="font-weight:bolder; font-size:22px;">CityRep System</span></a>            
          </div>
          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <p style="text-align: center; font-weight:bolder; font-size:20px; color: white;"> 城市体征构建与认知系统 </p>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3 style="text-align: left;  font-size:15px; color: white;">目录</h3>
              <ul class="nav side-menu">
                <li><a><i class="fa fa-car"></i> 城市交通体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'traffic:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'traffic:representation_train' %}">表征建模</a></li>
                    <li><a href="{% url 'traffic:representation_pre' %}">表征展示</a></li>
                    <li><a href="{% url 'traffic:speed_prediction' %}">速度预测</a></li>
                    <li><a href="{% url 'traffic:route_plan' %}">路径规划</a></li>
                    <li><a href="{% url 'traffic:next_loc_prediction' %}">下一跳预测</a></li>
                    <li><a href="{% url 'traffic:accident' %}">事故推演</a></li>
                    </li>
                  </ul>
                </li>
                <li><a><i class="fa fa-male"></i> 城市人口体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'population:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'population:representation_train' %}">流动建模</a></li>
                    <li><a href="{% url 'population:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-line-chart"></i> 城市经济体征 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'economy:introduction' %}">相关介绍</a></li>
                    <li><a href="{% url 'economy:representation_train' %}">指标分析</a></li>
                    <li><a href="{% url 'economy:representation_pre' %}">体征应用</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
          </div>
          <nav class="navbar navbar-expand-lg">
            <div class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
                <span class="navbar-text mr-3" style="font-size: 16px;">当前在线： {{ request.user.username }}</span>
                <form action="{% url 'login:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link" style="font-size: 16px;">退出</button>
                </form>
              {% else %}
                <a href="{% url 'login:login' %}" class="btn btn-link">登录</a>
                <a href="{% url 'login:register' %}" class="btn btn-link">注册</a>
              {% endif %}
            </div>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Plain Page</h3>
            </div>
          </div>

          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12 col-sm-12  ">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Plain Page</h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Settings 1</a>
                          <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    Add content to the page ...
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->

    </div>
  </div>

  <!-- jQuery -->
  <script src=" {% static 'assets/js/jquery.min.js' %} "></script>
  <!-- Bootstrap -->
  <script src=" {% static 'assets/js/bootstrap.bundle.min.js' %} "></script>
  <!-- Dropzone.js -->
  <!-- <script src=" {% static 'assets/js/dropzone.min.js' %} "></script> -->
  <script src=" {% static 'assets/js/jquery.cookie.js' %} "></script>

  <!-- Custom Theme Scripts -->
  <script src=" {% static 'assets/js/custom.min.js' %} "></script>

</body>
</html>